import { createBoard } from '@wixc3/react-board';
import { ElementsTree } from '../../../components/elements-tree/elements-tree';

export default createBoard({
    name: 'ElementsTree',
    Board: () => <ElementsTree />,
    isSnippet: true,
    environmentProps: {
        canvasWidth: 720,
    },
    tags: [
        'l',
        'o',
        't',
        's',
        'o',
        'f',
        't',
        'a',
        'g',
        's',
        'elements',
        'elements tree',
        'tree',
        'alot of stuff',
        'abuse',
        'abuse elements',
        'abuse elements tree',
        'com',
        'eon',
        'du',
        'de',
        'just',
        'be',
        'too',
        'much',
        'already',
        'yaayyy',
        'nice',
        'noice',
    ],
});
